version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - ${PWD}/mount/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: docker
      MYSQL_PASSWORD: 1234
